//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolBooks.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reviews
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public string UserId { get; set; }
        [Required(ErrorMessage = "Review Title  is Required")]
        public string Title { get; set; }
        [Required(ErrorMessage = "Review Description  is Required")]
        public string Text { get; set; }
        public Nullable<byte> Rating { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Books Books { get; set; }
    }
}
